services:

  ## Klippy Service
  klipper:
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    logging:
      driver: none
    depends_on:
      init:
        condition: service_completed_successfully
    command: >
      -I printer_data/run/klipper.tty
      -a printer_data/run/klipper.sock
      printer_data/config/printer.cfg
      -l printer_data/logs/klippy.log
    volumes:
      - /dev:/dev
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
    network_mode: host

  ## WebApi Service
  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    depends_on:
      klipper:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config:/opt/printer_data/config
    network_mode: host

  ## Frontend Service
  fluidd:
    image: ghcr.io/fluidd-core/fluidd:latest
    restart: unless-stopped
    volumes:
      - ./config:/opt/printer_data/config
      - gcode:/opt/printer_data/gcodes
    network_mode: host

  ## uStreamer Service
  ustreamer:
    image: mkuf/ustreamer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    devices:
      - /dev/video_ustreamer:/dev/video0
      
  ## Initialization Service
  init:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/config
    volumes:
      - .:/prind

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
